x-devices-common: &devices-common
  depends_on:
    server:
      condition: service_healthy

x-devices-common-environment: &devices-common-environment
  SERVER_DISCOVERY_PORT: 30000 # Port on which the device will announce in broadcast
  # Broadcast address to which the device will announce itself. (May need to be changed due to some firewall configurations)
  DISCOVERY_BROADCAST_ADDR: &discovery-broadcast-address 255.255.255.255
  # Some device containers use this var name but the meaning is the same as DISCOVERY_BROADCAST_ADDR
  SERVER_DISCOVERY_ADDR: *discovery-broadcast-address

# This is a reusable piece of code that marks devices that are already registered to the server
x-device-already-registered-env: &device-already-registered-env
  SERVER_ADDRESS: server:3000

x-presence-sensor-common-env: &presence-sensor-common-env
  TARGET_CONDITION: Presence
  CONDITION_PROBABILITY: 33
  CONDITION_TEST_PERIOD_MS: 5000

name: "domoticasw-demo"

services:
  server:
    image: ventus218/domoticasw-server@sha256:f90d14df8db47413deb1ca0e2c1ce0b78ed097c8d701cea2a9311932c46277a3
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: wget --quiet --spider http://localhost:3000 || exit 1
      timeout: &timeout 10s
      start_period: *timeout
      start_interval: 1s
      interval: 15s
    ports:
      - ${PORT:-80}:3000
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      SERVER_PORT: 3000
      DISCOVERY_PORT: 30000
      JWT_SECRET: secret
      BASE_DELAY_MS: 100
      RANDOM_DELAY_MULTIPLIER_MS: 700

  mongo:
    image: mongo@sha256:bf41aa48a1cc0ccc8e6071236acfc428b7110ec2cf14b47c8961bc472e2c7c61
    volumes:
      - ./dump:/data/dump
      - ./dump:/dump
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: mongosh --quiet --eval "db.runCommand('ping').ok" || exit 1
      timeout: &timeout 15s
      start_period: *timeout
      start_interval: 1s
      interval: 15s
    environment:
      - DUMP_DB=${DUMP_DB:-false}
    pre_stop:
      - command: sh -c "if [ "$${DUMP_DB}" = "true" ]; then mongodump --out /dump; fi"

  # ***** SIMULATED DEVICES *****

  # ***** ROOMBAS *****
  roomba:
    image: ventus218/domoticasw-roomba@sha256:087e4810f981c90cde4fa8678ab8eccf42ae31f36b103385913d451343ce8048
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ROOMS: Kitchen, Parents room, Living room, Children room
      INIT_ROOM: Living room
      CHARGING_ROOM: Living room
      STATE: Charging
      LAN_HOSTNAME: roomba

  # ***** MUSIC PLAYERS *****
  music-player:
    image: corradostortini2/domoticasw-music-player@sha256:e603aa4692663f0c0aa7d35277074df4864aca2d7a476427cd16f774fa048dfa
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      LAN_HOSTNAME: music-player
      MUSICS: "Back in Black-255,Must Have Been the Wind-243,Eye of the Tiger-246,Don't Stop Me Now-209,INVISIBLE-191"

  # ***** LIGHT SENSORS *****
  light-sensor:
    image: corradostortini2/domoticasw-light-sensor@sha256:940383813d6c186ed32b894966568e6fe3ef94d808845f9f568ec8492f511592
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      LAN_HOSTNAME: light-sensor
      UPDATE_RATE: 12000

  # ***** PRESENCE SENSORS *****
  presence-sensor:
    image: &boolean-sensor-image ventus218/domoticasw-boolean-sensor@sha256:70a19a1f4f5bcf109b4d1652e6a7974b0213b00d969779260344c5d5aef8ef1e
    <<: *devices-common
    environment:
      <<:
        [
          *devices-common-environment,
          *presence-sensor-common-env,
          *device-already-registered-env,
        ]
      LAN_HOSTNAME: presence-sensor
      ID: presence-sensor

  presence-sensor-1:
    image: *boolean-sensor-image
    <<: *devices-common
    environment:
      <<:
        [
          *devices-common-environment,
          *presence-sensor-common-env,
          *device-already-registered-env,
        ]
      LAN_HOSTNAME: presence-sensor-1
      ID: presence-sensor-1

  presence-sensor-2:
    image: *boolean-sensor-image
    <<: *devices-common
    environment:
      <<:
        [
          *devices-common-environment,
          *presence-sensor-common-env,
          *device-already-registered-env,
        ]
      LAN_HOSTNAME: presence-sensor-2
      ID: presence-sensor-2

  presence-sensor-3:
    image: *boolean-sensor-image
    <<: *devices-common
    environment:
      <<:
        [
          *devices-common-environment,
          *presence-sensor-common-env,
          *device-already-registered-env,
        ]
      LAN_HOSTNAME: presence-sensor-3
      ID: presence-sensor-3

  presence-sensor-4:
    image: *boolean-sensor-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *presence-sensor-common-env]
      LAN_HOSTNAME: presence-sensor-4
      ID: presence-sensor-4

  # ***** RAIN SENSORS *****
  rain-sensor:
    image: *boolean-sensor-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      LAN_HOSTNAME: rain-sensor
      ID: rain-sensor
      TARGET_CONDITION: Rain
      CONDITION_PROBABILITY: 25
      CONDITION_TEST_PERIOD_MS: 5000

  # ***** WASHING MACHINES *****
  washing-machine:
    image: marcoraggio/domoticasw-washing-machine@sha256:0f5b111e190b20eed62e9be7ec6db7306f146960da40257a6dbee18339e7f014
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      LAN_HOSTNAME: washing-machine

  # ***** SMART WINDOWS *****
  smart-window:
    image: &smart-window-image marcoraggio/domoticasw-window@sha256:9e6cbd82973ab3115a3bdfbb43be56a16e3855ff5bfc45972255a2338060bbf5
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: sm_000
      LAN_HOSTNAME: smart-window

  smart-window-1:
    image: *smart-window-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: sm_001
      LAN_HOSTNAME: smart-window-1

  # ***** LAMPS *****
  lamp:
    image: &lamp-image fracarluccii/domoticasw-lamp@sha256:b52f41da38732ef2c9e9582ab71dfd1648192be8d4c8a62c664b9d4cf7adb8e4
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: lamp
      LAN_HOSTNAME: lamp

  lamp-1:
    image: *lamp-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: lamp-1
      LAN_HOSTNAME: lamp-1

  lamp-2:
    image: *lamp-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: lamp-2
      LAN_HOSTNAME: lamp-2

  lamp-3:
    image: *lamp-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: lamp-3
      LAN_HOSTNAME: lamp-3

  lamp-4:
    image: *lamp-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment]
      ID: lamp-4
      LAN_HOSTNAME: lamp-4

  # ***** THERMOMETERS *****
  thermometer:
    image: &thermometer-image fracarluccii/domoticasw-thermometer@sha256:271b83722a4e1818c1494a5fecdbe1138731a771282a1f2a2cd7c7a1f7e8d70d
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: thermometer
      LAN_HOSTNAME: thermometer

  thermometer-1:
    image: *thermometer-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: thermometer-1
      LAN_HOSTNAME: thermometer-1

  thermometer-2:
    image: *thermometer-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: thermometer-2
      LAN_HOSTNAME: thermometer-2

  thermometer-3:
    image: *thermometer-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment, *device-already-registered-env]
      ID: thermometer-3
      LAN_HOSTNAME: thermometer-3

  thermometer-4:
    image: *thermometer-image
    <<: *devices-common
    environment:
      <<: [*devices-common-environment]
      ID: thermometer-4
      LAN_HOSTNAME: thermometer-4
